# 1. 넘파이(Numpy, Numerical Python)

In [1]:
import numpy as np

### 1) ndarray(Numpy Dimensional Array)

In [2]:
# Array 생성
a = np.array([1,2,3,4], float)
a

array([1., 2., 3., 4.])

In [3]:
a.shape     # 1차원 - vector 라고 함

(4,)

In [4]:
a.dtype     # float64 - double precision

dtype('float64')

In [5]:
a[0], a[3], a[-1]

(1.0, 4.0, 4.0)

In [6]:
# 2차원 어레이(Matrix)
mat = [[1,2,3,4], [5,6,7,8]]
b = np.array(mat)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
b.shape, b.dtype

((2, 4), dtype('int64'))

In [8]:
b = np.arange(1,9).reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# 3차원 어레이(Tensor)
c = np.arange(1,25).reshape(2,3,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [10]:
c.shape

(2, 3, 4)

In [11]:
c.size

24

In [12]:
# data type
np.array([[1, 2, 3], [4.5, '5', '6']], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [13]:
# shape 변경 - 엘리먼트의 갯수가 동일
c.reshape(4, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [14]:
c.reshape(4, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [15]:
# flatten - 1차원으로 변경
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
b.flatten()         # b.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

### 2) Indexing & Slicing