# 사이킷런 맛보기
- 아이리스 데이터
- 결정트리, SVM 으로 분류

### 1. 전처리

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [5]:
type(iris)

sklearn.utils.Bunch

In [2]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
# Feature data, X - 4개의 피쳐를 갖고 있어 통상적으로 대문자로 표기
iris.data.shape

(150, 4)

In [4]:
# Feature names
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
# Target data, y - 1차원 벡터, 통상적으로 소문자로 표기
iris.target.shape

(150,)

In [7]:
# Target names
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
# Description
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [10]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  species
0                5.1               3.5  ...               0.2        0
1                4.9               3.0  ...               0.2        0
2                4.7               3.2  ...               0.2        0
3                4.6               3.1  ...               0.2        0
4                5.0               3.6  ...               0.2        0

[5 rows x 5 columns]

### 2. 학습과 테스트 데이터셋으로 분리

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.2, random_state=2021
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [12]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 2,
       2, 0, 2, 1, 1, 1, 0, 0])

In [16]:
import numpy as np
unique, counts = np.unique(y_test, return_counts=True)
unique, counts

(array([0, 1, 2]), array([14, 10,  6]))

In [19]:
# y 값의 분포를 균일하게 하려면 stratify 파라메터를 사용해야 함
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, stratify=iris.target, test_size=0.2, random_state=2021
)

In [20]:
unique, counts = np.unique(y_test, return_counts=True)
unique, counts

(array([0, 1, 2]), array([10, 10, 10]))

### 3. 머신러닝 알고리즘을 적용해 학습
- 결정 트리(Decision Tree)

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
# 객체 생성 - 모델 생성, 괄호 안은 Hyper-parameter
dt_clf = DecisionTreeClassifier(random_state=2021)

In [23]:
# 모델 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=2021, splitter='best')

- SVM(Support Vector Machine)

In [24]:
from sklearn.svm import SVC

In [25]:
sv_clf = SVC(random_state=2021)

In [26]:
sv_clf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=2021, shrinking=True,
    tol=0.001, verbose=False)

### 4. 학습된 모델을 기반으로 테스트 데이터에 대해 예측 수행

In [27]:
pred_dt = dt_clf.predict(X_test)

In [28]:
pred_sv = sv_clf.predict(X_test)

### 5. 예측값과 실제값을 비교해 모델 성능 평가

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
# 결정트리 모델의 정확도
score = accuracy_score(y_test, pred_dt)
score

0.9

In [31]:
# 4, 5번 과정을 한꺼번에 수행
dt_clf.score(X_test, y_test)

0.9

In [32]:
# SVM 모델의 정확도
accuracy_score(y_test, pred_sv)

0.9

In [33]:
# 4, 5번 과정을 한꺼번에 수행
sv_clf.score(X_test, y_test)

0.9

In [34]:
# 예측 결과 리뷰
df = pd.DataFrame({
    '실제값': y_test, '결정트리': pred_dt, 'SVM': pred_sv
})
df

실제값  결정트리  SVM
0     0     0    0
1     1     1    1
2     1     2    1
3     2     2    2
4     0     0    0
5     1     1    1
6     0     0    0
7     1     1    1
8     2     2    2
9     0     0    0
10    1     1    1
11    1     1    1
12    1     1    1
13    2     2    1
14    2     1    1
15    0     0    0
16    2     2    2
17    0     0    0
18    2     2    2
19    0     0    0
20    1     1    1
21    2     2    2
22    0     0    0
23    2     2    2
24    2     1    1
25    0     0    0
26    1     1    1
27    1     1    1
28    2     2    2
29    0     0    0